@echo off
echo [Tech-geo] Deploying backend functions...
set /p PROJECT_ID=Enter Supabase Project ID (or set SUPABASE_PROJECT_ID env var):

if "%PROJECT_ID%"=="" set PROJECT_ID=%SUPABASE_PROJECT_ID%
if "%PROJECT_ID%"=="" (echo Project ID required & exit /b 1)

echo.
echo [1/14] process-payment...
call supabase functions deploy process-payment --project-ref %PROJECT_ID%
echo [2/14] payment-callback...
call supabase functions deploy payment-callback --project-ref %PROJECT_ID%
echo [3/14] notify-order...
call supabase functions deploy notify-order --project-ref %PROJECT_ID%
echo [4/14] notify-contact...
call supabase functions deploy notify-contact --project-ref %PROJECT_ID%
echo [5/14] manage-order...
call supabase functions deploy manage-order --project-ref %PROJECT_ID%
echo [6/14] manage-product...
call supabase functions deploy manage-product --project-ref %PROJECT_ID%
echo [7/14] admin-stats...
call supabase functions deploy admin-stats --project-ref %PROJECT_ID%
echo [8/14] search...
call supabase functions deploy search --project-ref %PROJECT_ID%
echo [9/14] newsletter...
call supabase functions deploy newsletter --project-ref %PROJECT_ID%
echo [10/14] generate-receipt...
call supabase functions deploy generate-receipt --project-ref %PROJECT_ID%
echo [11/14] coupons...
call supabase functions deploy coupons --project-ref %PROJECT_ID%
echo [12/14] analytics...
call supabase functions deploy analytics --project-ref %PROJECT_ID%
echo [13/14] check-stock...
call supabase functions deploy check-stock --project-ref %PROJECT_ID%
echo [14/14] resize-image...
call supabase functions deploy resize-image --project-ref %PROJECT_ID%

echo.
echo [Tech-geo] All functions deployed!
